version: 2.1

orbs:
  rust: phoenix-rs/rust@0.1.0

workflows:
  ci:
    jobs:
      - rust/lint-test-build:
          matrix:
            parameters:
              target:
                - linux-amd64
                - linux-arm64
          rust_version: "1.65"
