version: 2.1

orbs:
  rust: phoenix-rs/rust@0.1.1

workflows:
  ci:
    jobs:
      - rust/lint-test-build:
          matrix:
            parameters:
              target:
                - rust/linux-amd64
                - rust/linux-arm64
          rust_version: "1.65"
          release: false
